import { withBasePath } from "./base-path";

/** Local product & brand images (mixed with Hyundai CDN where noted). */
export const MEDIA = {
  engine: withBasePath("/images/products/engine/generator-engine.png"),
  garbage: withBasePath("/images/products/special/garbage-hd260.png"),
  garbageAlt: withBasePath("/images/products/special/garbage-key.jpg"),
  universalChassis: withBasePath("/images/products/chassis/universal-chassis.jpg"),
  chassis1: withBasePath("/images/products/chassis/bare-chassis-1.png"),
  chassis2: withBasePath("/images/products/chassis/bare-chassis-2.png"),
  cabSuper: withBasePath("/images/products/cab/super-cab.png"),
  cabXcient: withBasePath("/images/products/cab/xcient-interior.png"),
  truckHd72: withBasePath("/images/products/truck/hd72.png"),
  craneHd170: withBasePath("/images/products/crane/hd170-1000.png"),
  craneKnuckle: withBasePath("/images/products/crane/knuckle-crane.png"),
  craneStiff: withBasePath("/images/products/crane/stiff-crane.png"),
  wreckerHd260: withBasePath("/images/products/special/wrecker-hd260.png"),
  wreckerHd72: withBasePath("/images/products/special/wrecker-hd72.png"),
  roadSweeper: withBasePath("/images/products/special/road-sweeper.png"),
  busLineup: withBasePath("/images/products/bus/lineup.png"),
  busAeroTown: withBasePath("/images/products/bus/aero-town.png"),
  busAeroCity: withBasePath("/images/products/bus/aero-city.png"),
  busAeroExpress: withBasePath("/images/products/bus/aero-express.png"),
  tractorXcient: withBasePath("/images/products/tractor/xcient-fuel-cell.png"),
  brandCv: withBasePath("/images/brand/hyundai-cv/overview.png"),
  brandDesignKv: withBasePath("/images/brand/design/detail-kv.png"),
  brandDesignTilt: withBasePath("/images/brand/design/tilting-cab.png"),
  brandDesignFrame: withBasePath("/images/brand/design/strong-frame.png"),
  brandDesignRigid: withBasePath("/images/brand/design/rigid-construction.png"),
  brandTechAdas: withBasePath("/images/brand/technology/adas.png"),
  brandTechCyber: withBasePath("/images/brand/technology/cybersecurity.png"),
  brandTechEco: withBasePath("/images/brand/technology/economical.png"),
  brandTechMgmt: withBasePath("/images/brand/technology/efficient-mgmt.png"),
  brandComfortNvh: withBasePath("/images/brand/comfort/nvh.png"),
  brandComfortDash: withBasePath("/images/brand/comfort/dashboard.png"),
  newsXcient: withBasePath("/images/news/xcient-fuel-cell.png"),
  heroXcientBridge: withBasePath("/images/hero/xcient-hero-bridge.png"),
  heroXcientFleet: withBasePath("/images/hero/xcient-hero-fleet.png"),
  heroXcientProfile: withBasePath("/images/hero/xcient-hero-profile.png"),
  modelGt5: withBasePath("/images/models/gt5.png"),
  modelGt8: withBasePath("/images/models/gt8.png"),
  modelGt10: withBasePath("/images/models/gt10.png"),
  modelGt12: withBasePath("/images/models/gt12.png"),
} as const;
